# Generated by Django 4.2.6 on 2023-10-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_title", models.CharField(max_length=255)),
                ("reviewer_name", models.CharField(max_length=150)),
                ("review_score", models.IntegerField()),
                ("review_summary", models.CharField(max_length=255)),
                ("review_text", models.TextField()),
                ("review_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
