# Generated by Django 4.2.6 on 2023-10-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("author", models.CharField(max_length=255)),
                ("image_link", models.URLField()),
                ("preview_link", models.URLField()),
                ("publisher", models.CharField(max_length=255)),
                ("year_of_published", models.IntegerField()),
                ("info_link", models.URLField()),
                ("category", models.CharField(max_length=255)),
                ("rating", models.IntegerField()),
            ],
        ),
    ]
