# Generated by Django 4.2.4 on 2023-10-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='info_link',
        ),
        migrations.RemoveField(
            model_name='book',
            name='preview_link',
        ),
    ]
