# Generated by Django 4.2.6 on 2023-10-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reccomendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('another_book_title', models.CharField(max_length=255)),
                ('reccomender_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('reccomendation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
