# Generated by Django 4.2.6 on 2023-10-22 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_reccomendation_reccomendation_scale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reccomendation',
            new_name='Recomendation',
        ),
        migrations.RenameField(
            model_name='recomendation',
            old_name='reccomendation_date',
            new_name='recomendation_date',
        ),
        migrations.RenameField(
            model_name='recomendation',
            old_name='reccomendation_scale',
            new_name='recomendation_scale',
        ),
        migrations.RenameField(
            model_name='recomendation',
            old_name='reccomender_name',
            new_name='recomender_name',
        ),
    ]
