# Generated by Django 4.2.6 on 2023-10-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_rename_reccomendation_recomendation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recomendation',
            new_name='Recommendation',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='recomendation_date',
            new_name='recommendation_date',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='recomendation_scale',
            new_name='recommendation_scale',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='recomender_name',
            new_name='recommender_name',
        ),
    ]
